### ISSUE TITLE
[Feature] --> Add Huber Regression Algorithm to the ML/Algorithms/Regressions Repository 

### ISSUE THREAD

**Issue by UTSAVS26** [Avdhesh-Varshney/AI-Code#11]
## Summary:
Add an implementation of the Huber Regression algorithm to enhance the regression models available in the repository. Huber Regression is a robust linear regression technique that balances the characteristics of least squares and least absolute deviations, making it less sensitive to outliers.

## Details:
**Implementation Tasks:**
- Develop a new file named `HuberRegression.py` containing the Huber Regression algorithm.
- Create unit tests for the Huber Regression in `test_HuberRegression.py`.
- Update the README.md file to include:
  - Usage instructions
  - Explanation of parameters
  - Installation guide
  - Information about running tests

**Contributor:**
[Utsav Singhal](https://github.com/UTSAVS26)

**Associated Issues:**
None

**Testing Plan:**
- Add unit tests for the Huber Regression algorithm, runnable with `python -m unittest test_HuberRegression.py`.
- Ensure the implementation is tested locally to verify correctness and functionality.

This enhancement aims to provide a more comprehensive set of regression tools for users, enriching their machine learning toolkit.

**Request:**
Please assign this issue to me under SSOC'24. I intend to add the necessary Python programs to this directory.

**Contact Information:**
LinkedIn: [Utsav Singhal](https://www.linkedin.com/in/utsavsinghal2604/)

**Comment by Avdhesh-Varshney** [comment]
@UTSAVS26 go ahead.
