### ISSUE TITLE
Addition of Introduction to NLP and Setup of NLTK Library

### ISSUE THREAD

**Issue by Praneet0327** [Avdhesh-Varshney/AI-Code#12]
### **Objective:**
To introduce the basic concepts of Natural Language Processing (NLP) and provide a comprehensive guide to setting up the NLTK (Natural Language Toolkit) library. This will lay a strong foundation for understanding and implementing more advanced NLP concepts and techniques.

### **Background:**
Natural Language Processing (NLP) is a critical field in Artificial Intelligence (AI) that deals with the interaction between computers and human (natural) languages. Understanding the basic concepts of NLP is essential for anyone looking to delve into more complex NLP tasks such as sentiment analysis, machine translation, and question-answering systems. The NLTK library is a powerful tool that provides easy-to-use interfaces to over 50 corpora and lexical resources, along with a suite of text processing libraries for classification, tokenization, stemming, tagging, parsing, and semantic reasoning.

### **Tasks:**
- Define NLP and its importance.
- Discuss the history and evolution of NLP.
- Explain key concepts and terminology used in NLP (e.g., tokens, corpus, stopwords, stemming, lemmatization, etc.).
- Provide step-by-step instructions for installing the NLTK library.
- Demonstrate basic usage of NLTK with examples (e.g., tokenization, stemming, lemmatization).

Kindly assign me this issue under SSOC'24
Thank you

**Comment by Avdhesh-Varshney** [comment]
@Praneet0327 go ahead.
