### ISSUE TITLE
Add New Loss Functions 

### ISSUE THREAD

**Issue by bhanushri12** [Avdhesh-Varshney/AI-Code#13]
@Avdhesh-Varshney 
I propose adding two new loss functions, Root Mean Squared Error (RMSE) and Mean Absolute Error (MAE), to the `ML -> algorithms -> Losses` folder. These loss functions are widely used in regression tasks and will enhance the repository by providing more options for error measurement.

## Motivation

Currently, the repository might lack some fundamental loss functions that are crucial for regression tasks. Adding RMSE and MAE will provide more flexibility and utility for users who are working on regression problems.

**Comment by Avdhesh-Varshney** [comment]
@bhanushri12 go ahead.
