### ISSUE TITLE
Adding DCGAN Model for cats and dogs dataset

### ISSUE THREAD

**Issue by adi271001** [Avdhesh-Varshney/AI-Code#17]
i wanted to help people by  implementing  dcgan model using the cats and dogs dataset and help them understand this type of GAN and can further implement it for other projects

**Comment by adi271001** [comment]
@Avdhesh-Varshney please assign this to me under ssoc 2024

**Comment by Avdhesh-Varshney** [comment]
@adi271001 This repository is not for the purpose of project addition. But it consists of just guidelines for a learner how to approach any project?
@pawaspy Issues are assigned on the basis of FCFS.
Both of you join the project discord server as i am creating a meeting on today for project movement. Link is present in Main readme file.
