### ISSUE TITLE
[FEATURE REQUEST] Adding Pre-Processing Techniques for numerical as well as categorical features

### ISSUE THREAD

**Issue by Lycons-rage** [Avdhesh-Varshney/AI-Code#18]
# Summary
Implement the concepts of various Data Preprocessing and handling techniques for both numerical as well as categorical features which improves model performance, convergence speed, interpretability, and ensures equal feature contribution by scaling features to a similar range.

# Implementation
 - Develop various python files for Stadardization, Normalization, Categorical preprocessing such as Rank based ordinal encoding, one hot encoding
 - Write all the neccessary documentations
 - Local testing of developed python code to ensure a bug-free approach
 
#### Contributor 
- [Chinmaya Tewari](https://github.com/Lycons-rage)
- Please assign this to me under SSoC 2024.

**Comment by Avdhesh-Varshney** [comment]
@Lycons-rage go ahead.
