### ISSUE TITLE
Addition of Various Text Preprocessing Techniques

### ISSUE THREAD

**Issue by Praneet0327** [Avdhesh-Varshney/AI-Code#19]
**The goal of this issue is to create a detailed guide on various text preprocessing techniques. This guide will serve as a foundational resource for users, helping them understand and implement essential preprocessing steps before applying more advanced Natural Language Processing (NLP) techniques.**

Kindly assign me this issue under SSOC'24
Thank you

**Comment by Avdhesh-Varshney** [comment]
@Praneet0327 go ahead.
