### ISSUE TITLE
Add python scripts for Dynamic Programming

### ISSUE THREAD

**Issue by imsuraj675** [Avdhesh-Varshney/AI-Code#21]
I want to add these programs in the specified directory. Please assign me this issue under SSOC'24

**Comment by Avdhesh-Varshney** [comment]
@imsuraj675 mention those programs first.

**Comment by imsuraj675** [comment]
The questions which I will add are:-
- Python Program to Print nth Fibonacci Number using Dynamic Programming with Memoization
- Python Program to Print nth Fibonacci Number using DP with Bottom-Up Approach
- Python Program to Solve Rod Cutting Problem using Dynamic Programming with Memoization
- Python Program to Solve Rod Cutting Problem using DP with Bottom-Up Approach
- Python Program to Solve 0-1 Knapsack Problem using DP with Memoization
- Python Program to Solve 0-1 Knapsack Problem using DP with Bottom-Up Approach
- Python Program to Solve Matrix-Chain Multiplication using DP with Memoization
- Python Program to Solve Matrix-Chain Multiplication using DP with Bottom-Up Approach
- Python Program to Find Longest Common Subsequence using Dynamic Programming with Memoization
- Python Program to Find Longest Common Subsequence using Dynamic Programming with Bottom-Up
Approach
- Python Program to Find Longest Common Substring using Dynamic Programming with Memoization
- Python Program to Find Longest Common Substring using Dynamic Programming with Bottom-Up
Approach
- Python Program to Count all Paths in a Grid with Holes using Dynamic Programming with Memoization
- Python Program to Count all Paths in a Grid with Holes using Dynamic Programming with Bottom-Up
Approach

**Comment by Avdhesh-Varshney** [comment]
@imsuraj675 go ahead.
