### ISSUE TITLE
[Feature] --> Add Various Generative Adversarial Network (GAN) Architectures to the GAN/Algorithms/Repository

### ISSUE THREAD

**Issue by UTSAVS26** [Avdhesh-Varshney/AI-Code#22]
## Summary:
Introduce various Generative Adversarial Network (GAN) architectures and their applications in medical imaging, with a focus on enhancing diagnostic accuracy and addressing data scarcity and privacy concerns. Additionally, propose the implementation of a basic GAN model alongside Huber Regression to enrich the repository's machine learning toolkit.

## Details:
**Implementation Tasks:**
1. Provide an overview of GAN architectures and their relevance in medical imaging.
2. Develop a new file named BasicGAN.py containing a basic GAN model for generating synthetic medical images.
3. Create unit tests for the Basic GAN in test_BasicGAN.py.
4. Update the README.md file to include:
   - Usage instructions for Basic GAN.
   - Explanation of parameters for model.
   - Installation guide for the repository.
   - Information about running tests.
5. Attach an image illustrating nine different GAN model architectures, including Vanilla GAN, cGANs, EBGAN/BEGAN, InfoGAN, ACGAN, and VAEGAN.
7. Plan to implement each GAN model discussed above with different medical field datasets, enhancing the repository's diversity and utility.

![image](https://github.com/Avdhesh-Varshney/AI-Code/assets/119779889/2a1f2239-a770-478b-ab60-9213cb03a6d1)

**Contributor:**
[Utsav Singhal](https://www.github.com/UTSAVS26/)

**Associated Issues:**
None

**Testing Plan:**

- Add unit tests for the Basic GAN algorithm, runnable with python -m unittest test_BasicGAN.py.
- Ensure the implementation is tested locally to verify correctness and functionality.

This enhancement aims to provide a comprehensive set of GAN models for medical imaging applications.

**Request:**
Please assign this issue to me under SSOC'24. I intend to add the necessary Python programs to this directory.

**Contact Information:**
LinkedIn: [Utsav Singhal](https://www.linkedin.com/in/utsavsinghal2604/)

**Comment by Avdhesh-Varshney** [comment]
@UTSAVS26 go ahead.

**Comment by UTSAVS26** [comment]
@Avdhesh-Varshney Sorry for the delay in the work. Here's the pull request for this issue raised #55, please review it.
