### ISSUE TITLE
📃: Adding Bag of words(BoW) algorithm Under NLP 

### ISSUE THREAD

**Issue by Arushi-N4** [Avdhesh-Varshney/AI-Code#24]
:red_circle: **Bag of words(BoW) algorithm** :
:red_circle: **I would like to add basic Python code( under NLP folder) for text preprocessing, bag-of-words representation, and TF-IDF transformation using scikit-learn from juptyer notebook to give reader simple understanding. It preprocesses text data by converting it to lowercase and removing non-alphabetic characters and utilizes CountVectorizer to create a bag-of-words representation of the data. Also calculates TF-IDF scores using TfidfTransformer** :

### Screenshots 📷

<img width="507" alt="image" src="https://github.com/Avdhesh-Varshney/AI-Code/assets/145531852/89e049c8-916a-4ec6-9269-4b79336f871b">

After BoW algo:-
<img width="448" alt="image" src="https://github.com/Avdhesh-Varshney/AI-Code/assets/145531852/66d4d981-a643-4c8c-9826-a1e1052d9ee0">

Full name : Arushi Nirala
Participant role-SSOC 2024

**Comment by Avdhesh-Varshney** [comment]
@Arushi-N4 go ahead. And carefully follow the guidelines
