### ISSUE TITLE
🐛: Explain NLTK setup

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/AI-Code#26]
:red_circle: **Title** : Explanation of NLTK setup
:red_circle: **Bug** : Replace this [notebook](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/NLP/Algorithms/Installation_set-up_NLTK.ipynb) by a directory `NLTK Setup`
:red_circle: **Changes** :  
1. remove this notebook file.
2. create a directory named `NLTK setup`
3. provide the code for different setups of different topics from the provided notebook.
4. add a readme file to explain the provided code.
5. create another sub-directory named `tests` which consists the python file to test them

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by jyo-02** [comment]
hi, i would like to try resolving this issue. could you please assign me this? also, if you have any tips or specific areas you'd like me to focus on, feel free to let me know. I'm here to learn!
Name: Jyotiska Bose
Participant role: SSOC

**Comment by shivansh-2003** [comment]
Shivansh Mahajan
Participation role :- SSOC
I am well equiped with nlp , you can se my nlp repository https://github.com/shivansh-2003/NLP.

**Comment by Avdhesh-Varshney** [comment]
@shivansh-2003 your repo is not required. you have to explain the provided notebook code into a readme file. By deleting this notebook, add readme in the documentation directory only.

**Comment by shivansh-2003** [comment]
sir in this task i want clarity list of works 
delete notebook file
create a readme file out of notebook file name:- NLTK_setup.md to add in documentation section
any other task please mention

**Comment by Avdhesh-Varshney** [comment]
No, nothing else, But keep everything from notebook into a md file. Name = `NLTK-Setup.md`.
