### ISSUE TITLE
Add Python scripts\Python Programs\Factorial & Fibonacci Programs in Python

### ISSUE THREAD

**Issue by imsuraj675** [Avdhesh-Varshney/AI-Code#3]
Please assign me this issue under SSOC'24. I want to add the required python programs for this directory.
My linkedIn profile - https://www.linkedin.com/in/kashyapsuraj/

**Comment by Aditya-Garg-01** [comment]
please assign me this i can add these codes it will take around some hours only

**Comment by AbhishekMohanKr** [comment]
I want to know more about this project and work along with you. Please assign me this repo to work upon it.

**Comment by Avdhesh-Varshney** [comment]
Python scripts is not for adding the small programs or any addition of cp problems.
- It consists of addition of some special programs or innovative thinking codes only.
- So, don't raise the issues for these silly programs.

**Comment by imsuraj675** [comment]
Ok, I apologize for that, can you clarify some of my doubts:

1. How can I contribute in this project in writing python programs, as I
have seen many python programs are not implemented for example problems on
DP, Problems on Sorting etc...

2. I am not able to find any Readme.md file for Preprocessing and NLP
directory, so how can I contribute in these two things.

Thanks in advance
