### ISSUE TITLE
📃: Addition of ranking losses

### ISSUE THREAD

**Issue by Mayureshd-18** [Avdhesh-Varshney/AI-Code#32]
:red_circle: **Title** : Addition of ranking losses
:red_circle: **Aim** : Add ranking losses like Triplet Loss and Pairwise Ranking Loss
:red_circle: **Brief Explanation** : The repo contains some of the regression as well as classification losses, but is missing ranking losses. I would like to add them. Please assign this @Avdhesh-Varshney if you think this is a valuable contribution

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mayuresh Dharwadkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Mayureshd-18  go ahead.
