### ISSUE TITLE
📃:  Python Program Addition for MatPlotlib

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/AI-Code#34]
:red_circle: **Title** : Python Program Addition for MatPlotlib
:red_circle: **Aim** : Python Program Addition for MatPlotlib
:red_circle: **Brief Explanation** : Matplotlib is python library used to create the graph for several scenarioes.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/AI-Code/assets/119414762/da7ae24c-06c0-4ba8-9217-2b57cf7c740a)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
