### ISSUE TITLE
📃: Twitter sentiment analysis model

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/AI-Code#41]
:red_circle: **Title** : Twitter sentiment analysis model
:red_circle: **Aim** : Brief approach for this project from a basic level upto highest possible accuracy.
:red_circle: **Brief Explanation** : 
- Link of the dataset
- Perfoming EDA
- Attach any blog for reading related to the topic
- Explain the features properly
- Add necessary comments for the code understanding
- Attach your notebook links
- Applying atleast 3-4 models and compairing them.

**NOTE:** *Follow this [readme template](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/PROJECT-README-TEMPLATE.md)*

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by devil-90** [comment]
✅ To be Mentioned while taking the issue :

Full name : Billinty varra laya
What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.): vsoc

**Comment by Avdhesh-Varshney** [comment]
@devil-90 go ahead.
