### ISSUE TITLE
[Feature]--> Addition in ML - Algorithms under Regressions

### ISSUE THREAD

**Issue by KamakshiOjha** [Avdhesh-Varshney/AI-Code#5]
Project Description: Elastic Net Regression Implementation and Testing

The objective of this project is to implement the Elastic Net Regression algorithm from scratch and compare its performance with the Elastic Net implementation provided by scikit-learn. Elastic Net Regression combines the properties of both L1 (Lasso) and L2 (Ridge) regularizations, providing a balanced approach that can handle both feature selection and multicollinearity.

Goals --> 
1. Implement Elastic Net Regression: Develop a custom Python class that performs Elastic Net Regression, incorporating both L1 and L2 regularization terms.
2. Test the Implementation: Create unit tests to ensure that the custom implementation produces results comparable to the well-established scikit-learn's Elastic Net model.
3. Evaluate Performance: Assess the performance and accuracy of the custom model by using synthetic data and comparing predictions with the scikit-learn model.

please assign me this issue under SSOC.
Thank you!

**Comment by UTSAVS26** [comment]
Add ElasticNet Regression implementation

### Description:
This pull request adds an implementation of the ElasticNet Regression algorithm to the repository. ElasticNet Regression is a linear regression model with combined L1 and L2 regularization, providing a balance between Lasso and Ridge regression.

### Changes:
- Added a new file named `ElasticNetRegression.py` containing the implementation of ElasticNet Regression.
- Created unit tests for ElasticNet Regression in `test_ElasticNetRegression.py`.
- Updated the README.md file with usage instructions, parameters explanation, installation guide, and information about running tests.

### Contributor:
[Utsav Singhal](https://github.com/UTSAVS26)

### Associated Issues:
None

### Testing:
- Unit tests for ElasticNet Regression have been added and can be run using `python -m unittest test_ElasticNetRegression.py`.
- The implementation has been tested locally to ensure correctness and functionality.

This contribution aims to expand the collection of regression algorithms available in the repository, providing users with more options for their machine learning tasks. Thank you for considering this pull request!

Please assign me this issue under SSOC'24. I want to add the required python programs for this directory.
My linkedin profile: https://www.linkedin.com/in/utsavsinghal2604/

**Comment by Avdhesh-Varshney** [comment]
@KamakshiOjha Assigned to you. Go ahead.

**Comment by UTSAVS26** [comment]
## Project: Add Huber Regression Implementation and Testing

### Description:
This pull request adds an implementation of the Huber Regression algorithm to the repository. Huber Regression is a robust linear regression model that combines the properties of least squares and least absolute deviations, reducing the influence of outliers in the dataset.

### Changes:
- Added a new file named `HuberRegression.py` containing the implementation of Huber Regression.
- Created unit tests for Huber Regression in `test_HuberRegression.py`.
- Updated the README.md file with usage instructions, parameters explanation, installation guide, and information about running tests.

### Contributor:
[Utsav Singhal](https://github.com/UTSAVS26)

### Associated Issues:
None

### Testing:
- Unit tests for Huber Regression have been added and can be run using `python -m unittest test_HuberRegression.py`.
- The implementation has been tested locally to ensure correctness and functionality.

This contribution aims to expand the collection of regression algorithms available in the repository, providing users with more options for their machine learning tasks. Thank you for considering this pull request!

Please assign me this issue under SSOC'24. I want to add the required python programs for this directory.
My LinkedIn profile: https://www.linkedin.com/in/utsavsinghal2604/

**Comment by UTSAVS26** [comment]
## Project: Add Isotonic Regression Implementation and Testing 

### Description:
This pull request adds an implementation of the Isotonic Regression algorithm to the repository. Isotonic Regression is a non-parametric regression technique that fits a non-decreasing function to the data, making it useful for tasks where monotonicity is a constraint.

### Changes:
- Added a new file named `IsotonicRegression.py` containing the implementation of Isotonic Regression.
- Created unit tests for Isotonic Regression in `test_IsotonicRegression.py`.
- Updated the README.md file with usage instructions, parameters explanation, installation guide, and information about running tests.

### Contributor:
[Utsav Singhal](https://github.com/UTSAVS26)

### Associated Issues:
None

### Testing:
- Unit tests for Isotonic Regression have been added and can be run using `python -m unittest test_IsotonicRegression.py`.
- The implementation has been tested locally to ensure correctness and functionality.

This contribution aims to expand the collection of regression algorithms available in the repository, providing users with more options for their machine learning tasks. Thank you for considering this pull request!

Please assign me this issue under SSOC'24. I want to add the required python programs for this directory.
My LinkedIn profile: https://www.linkedin.com/in/utsavsinghal2604/
