### ISSUE TITLE
📃: Music Genre Classification Model

### ISSUE THREAD

**Issue by ArchitJ6** [Avdhesh-Varshney/AI-Code#52]
🔴 Title : Music Genre Classification Model
🔴 Aim : Develop a model to classify songs into different genres based on audio features.
🔴 Brief Explanation :

Link of the dataset
Perfoming EDA
Attach any blog for reading related to the topic
Explain the features properly
Add necessary comments for the code understanding
Attach your notebook links
Applying atleast 3-4 models and compairing them.
NOTE: Follow this [readme template](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/PROJECT-README-TEMPLATE.md)

Screenshots 📷
✅ To be Mentioned while taking the issue :

Full name :
What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by fspzar123** [comment]
Full name : Filbert Shawn 
What is your participant role? SSOC' 24
**Data Collection:** I will use datasets like the GTZAN genre dataset, which contains audio files of various genres.
Link - [GTZAN Dataset](https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification/data)
**Feature Extraction:** Use a library like _librosa_ to extract audio features such as

> - Mel-frequency cepstral coefficients (MFCC)
> - Chromagram
> - Spectral contrast
> - Tonnetz
> - Zero-crossing rate,
> - Tempo

**Data Preprocessing:** Normalize the features and handle missing values. Ensure the dataset is balanced.
**Model Selection:** Starting with a simple model like a Decision Tree, and then move to more complex models like Random Forest, Support Vector Machine (SVM), or Neural Networks.
**Training and Evaluation:** Split the data into training and testing sets. Using metrics like accuracy, precision, recall, and F1-score for evaluation.

**Comment by Avdhesh-Varshney** [comment]
@fspzar123 go ahead. And take refence for contribution [type](https://github.com/Avdhesh-Varshney/AI-Code/tree/main/Pre-Processing/Projects/bangladesh_premier_league_analysis)
