### ISSUE TITLE
🧑‍💻:  I want to modify the readme file. My email id : iammeghdeb@gmail.com. I got this from Social Summer of Code 2024. My github handle https://github.com/Megh2005

### ISSUE THREAD

**Issue by Megh2005** [Avdhesh-Varshney/AI-Code#54]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** :  
- I want to change the look of the readme
- I am going to change the entire styling 
- [Click]:(https://github.com/Megh2005) you can check my repos readme designs

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Megh Deb 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ArchitJ6** [comment]
Could you please specify which readme you're referring to? Are you looking to update the project's main readme, a specific module's readme, or another readme file?

**Comment by Megh2005** [comment]
> Could you please specify which readme you're referring to? Are you looking to update the project's main readme, a specific module's readme, or another readme file?
![IMG_20240623_194908](https://github.com/Avdhesh-Varshney/AI-Code/assets/147889330/70156720-7ebe-44f9-8abe-50fb501daf02)
This one

**Comment by Avdhesh-Varshney** [comment]
@Megh2005 not required. focus on functional part contribution not on designing.
