### ISSUE TITLE
📃: Health Insurance Cross Sell Prediction

### ISSUE THREAD

**Issue by siddhant4ds** [Avdhesh-Varshney/AI-Code#74]
:red_circle: **Title** : Health Insurance Cross Sell Prediction
:red_circle: **Aim** : Building a model to predict whether a Health Insurance customer would be interested in Vehicle Insurance.
:red_circle: **Brief Explanation** :  
* Dataset: [Health Insurance Cross Sell Prediction](https://www.kaggle.com/datasets/anmolkumar/health-insurance-cross-sell-prediction/data)
* Performing EDA
* Attach your notebook links
* Applying at least 3-4 models and comparing them

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by siddhant4ds** [comment]
@Avdhesh-Varshney I would like to work on this issue. 

Since the dataset is relatively large, I can train neural network models to perform classification. This project can be added to the DL folder in that case.
If ML models are also required, I can add this to the ML folder.

Full name: Siddhant Tiwari
Participant role: SSOC-3 (2024)

**Comment by Avdhesh-Varshney** [comment]
@siddhant4ds go ahead. No model is not required. Just create a guide for the learners, how to approach these problems.

**Comment by siddhant4ds** [comment]
> @siddhant4ds go ahead. No model is not required. Just create a guide for the learners, how to approach these problems.

I meant that depending on the models in my linked notebook, the folder will be decided - ML, DL, Preprocessing, etc.

So which folder should I put this project in? I will create my notebook accordingly.

**Comment by Avdhesh-Varshney** [comment]
Yes, go with the labels.
