### ISSUE TITLE
📃: GloVe Algorithm, FastText Algorithm, and Word Embeddings Documentation

### ISSUE THREAD

**Issue by UTSAVS26** [Avdhesh-Varshney/AI-Code#76]
:red_circle: **Title** : GloVe Algorithm, FastText Algorithm, and Word Embeddings Documentation

:red_circle: **Aim** : To implement and demonstrate the GloVe and FastText algorithms for generating word embeddings and to provide comprehensive documentation on various word embedding techniques.

:red_circle: **Brief Explanation** : This issue involves three key tasks:
1. **GloVe Algorithm**: Implement and showcase the GloVe (Global Vectors for Word Representation) algorithm to generate word embeddings based on word co-occurrence statistics.
2. **FastText Algorithm**: Implement and demonstrate the FastText algorithm, which extends Word2Vec by including character n-grams to enhance the representation of rare words.
3. **Word Embeddings Documentation**: Create detailed documentation covering the theoretical background, implementation steps, and practical applications of word embedding methods such as Word2Vec, GloVe, and FastText.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Utsav Singhal
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@UTSAVS26 Looks good. Go ahead.

**Comment by UTSAVS26** [comment]
@Avdhesh-Varshney  Here's the pull request for this issue raised https://github.com/Avdhesh-Varshney/AI-Code/pull/77, please review it.
