### ISSUE TITLE
📃: Used Cars Price Prediction

### ISSUE THREAD

**Issue by siddhant4ds** [Avdhesh-Varshney/AI-Code#81]
:red_circle: **Title** : Used Cars Price Prediction
:red_circle: **Aim** : Predict the price of used cars based on its configuration and usage.
:red_circle: **Brief Explanation** :
Dataset: [Used Cars Price Prediction dataset](https://www.kaggle.com/datasets/avikasliwal/used-cars-price-prediction?select=train-data.csv)

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by siddhant4ds** [comment]
@Avdhesh-Varshney Kindly assign me this issue. Thanks.

Full name: Siddhant Tiwari
What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.): SSOC-3 (2024)

**Comment by siddhant4ds** [comment]
Since the deadline for SSOC has already arrived, I will not be able to work on it.

I am still interested in contributing for this issue after SSOC. So you can leave the issue assigned to me and remove the SSOC label. Thanks.

**Comment by Avdhesh-Varshney** [comment]
Np. Go ahead.
