### ISSUE TITLE
🐛: No requirements.txt

### ISSUE THREAD

**Issue by OkenHaha** [Avdhesh-Varshney/AI-Code#84]
:red_circle: **Title** : No requirements.txt
:red_circle: **Bug** : This isn't exactly a bug but rather a missing file. There's no requirements.txt to install the required dependencies. It'd be great if there's a common python version to use, along with suitable library versions being used to implement the training of the models.
:red_circle: **Changes** :   Testing on A working Python version along with the libraries and putting the required libraries along with their versions in a requirements.txt file. The python version being used or that was used should also be mentioned as this often sometimes conflict with available python libraries

### Screenshots 📷

![image](https://github.com/user-attachments/assets/71d786c3-c4be-41ca-9a69-59845306eace)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by OkenHaha** [comment]
@Avdhesh-Varshney I can work on this issue, if applicable, by assigning it to me.

**Comment by Avdhesh-Varshney** [comment]
@OkenHaha this is not an issue. Because there is no project is deployed or program is created. This repo is just for learning purpose only. It provides the guidance to all ML enthusiast to learn from scratch
